apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: suhat-ingress
spec:
  ingressClassName: kong
  rules:
  - http:
      paths:
      - path: /foo
        pathType: ImplementationSpecific
        backend:
          service:
            name: suhat-service
            port:
              number: 80